project:
  type: website
  output-dir: docs

website:
  title: "big data & R"
  site-url: https://nbc.gitlab-pages.din.developpement-durable.gouv.fr/big-data/docs
  sidebar:
    style: "docked"
    page-navigation: true
    search: true
    contents:
      - href: index.qmd
        text: "Les outils big data de R"
      - section: "Quelques documents en vracs"
        contents:
          - href: introduction-donnees-massives-arrow.qmd
            text: "Introduction à arrow"
          - href: introduction-duckdb.qmd
            text: "Introduction à duckdb"
          - href: cas-pratique-traitement-duckdb.qmd
            text: "Un exemple de conversion a duckdb"
          - href: conversion-fichier-sas.qmd
            text: "Notes sur la conversion de fichiers SAS"
      - section: "Présentations"
        contents:
          - href: presentation_insee.qmd
            text: "REX SDES - Présentation INSEE"
